name: security

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  schedule:
    - cron: '15 3 * * 1'   # every Monday at 03:15 UTC

permissions:
  contents: read
  security-events: write   # allow SARIF uploads
  id-token: write          # Trivy DB OIDC downloads
  actions: read

jobs:

  codeql:
    name: CodeQL Analysis
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Initialize CodeQL
        uses: github/codeql-action/init@v3
        with:
          languages: javascript
      - name: Autobuild project
        uses: github/codeql-action/autobuild@v3
      - name: Analyze code with CodeQL
        uses: github/codeql-action/analyze@v3

  semgrep:
    name: Semgrep SAST
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run Semgrep
        uses: returntocorp/semgrep-action@v1
        env:
          SEMGREP_APP_TOKEN: ${{ secrets.SEMGREP_APP_TOKEN }}

  sonarcloud:
    name: SonarCloud Quality Gate
    runs-on: ubuntu-latest
    env:
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
    steps:
      - uses: actions/checkout@v4
      - name: Run SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@v2
        with:
          args: >
            -Dsonar.organization=teerasak-mairoddee
            -Dsonar.projectKey=Teerasak-Mairoddee_actions

  trivy:
    name: Trivy Vulnerability Scan
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Run Trivy scan
        uses: aquasecurity/trivy-action@0.12.0
        with:
          image-ref: ghcr.io/aquasecurity/trivy:0.51.3
          scan-type: fs
          vuln-type: os,library
          ignore-unfixed: true
          severity: CRITICAL,HIGH,MEDIUM,LOW
          format: sarif
          output: trivy-results.sarif

      - name: Upload Trivy SARIF to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v3
        if: always()
        with:
          sarif_file: trivy-results.sarif

      - name: Notify n8n workflow
        if: always()
        run: |
          curl -s -o /dev/null -w "n8n we
